export enum ErrorCode {
  LOGIN_NOT_FOUND = 'LOGIN_NOT_FOUND',
  LOGIN_NOT_VALID = 'LOGIN_NOT_VALID',
  LOGIN_ROLE_INVALID = 'LOGIN_ROLE_INVALID',
  LOGIN_ALREADY_USED = 'LOGIN_ALREADY_USED',
  PASSWORD_INVALID = 'PASSWORD_INVALID',

  API_KEY_NOT_FOUND = 'API_KEY_NOT_FOUND',
}
