export enum ErrorCode {
  LOGIN_NOT_FOUND = 'LOGIN_NOT_FOUND',
  LOGIN_NOT_VALID = 'LOGIN_NOT_VALID',
  LOGIN_ROLE_INVALID = 'LOGIN_ROLE_INVALID',
  LOGIN_ALREADY_USED = 'LOGIN_ALREADY_USED',
  LOGIN_ALREADY_HAS_OTP = 'LOGIN_ALREADY_HAS_OTP',
  PASSWORD_INVALID = 'PASSWORD_INVALID',
  TOKEN_OTP_INVALID = 'TOKEN_OTP_INVALID'
}
