# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

# name: Node.js Package

# on:
#   push:
#     branches:
#       - main

# jobs:
#   publish-npm:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 16
#           registry-url: https://registry.npmjs.org/
#       - run: yarn install
#       - run: yarn build
#       - run: npm publish --access public
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.npm_token}}

# name: Node.js Package

# on:
#   push:
#     branches:
#       - main
#       - develop

# jobs:
#   publish-npm:
#     runs-on: ubuntu-latest

#     steps:
      
#         uses: actions/checkout@v2
#         uses: actions/setup-node@v3
#         with:
#           node-version: 16
#           registry-url: https://registry.npmjs.org/

#       - name: Set version match output variable
#         id: set-version-match
#         run: |
#           if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
#             VERSION_MATCH=$(jq -r '.version' package.json | grep -q '^[0-9]+\.[0-9]+\.[0-9]+$' && echo 'true' || echo 'false')
#             echo "::set-output name=match::${VERSION_MATCH}"
#           elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
#             VERSION_MATCH=$(jq -r '.version' package.json | grep -q '^[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+\.[0-9]+\.[0-9]+$' && echo 'true' || echo 'false')
#             echo "::set-output name=match::${VERSION_MATCH}"
#           fi

#   publish-condition:
#     needs: publish
#     runs-on: ubuntu-latest

#     steps:
#       - name: Display version match output
#         run: |
#           echo "Version match: ${{ needs.publish.outputs.match }}"

# - run: yarn install
# - run: yarn build
# - run: npm publish --access public

#  env:
#      NODE_AUTH_TOKEN: ${{secrets.npm_token}}

name: Conditional Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Specify the version'
        required: true
      target_branch:
        description: 'Specify the target branch'
        required: true
        default: 'main' # Set a default value, e.g., 'main'

jobs:
  conditional_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Target Branch
        id: set_branch
        run: echo "TARGET_BRANCH=${{ github.event.inputs.target_branch }}" >> $GITHUB_ENV

      - name: Conditional Step
        run: |
          if [[ "${{ github.event.inputs.version }}" == "1.0.0" ]]; then
            echo "true"
            if [[ "${{ env.TARGET_BRANCH }}" == "main" ]]; then
              echo "Running on main branch"
              # Add your main branch steps here
            else
              echo "Invalid target branch specified for version 1.0.0"
              exit 1
            fi
          elif [[ "${{ github.event.inputs.version }}" == "1.0.0-rc.1.0.0" ]]; then
            echo "true"
            if [[ "${{ env.TARGET_BRANCH }}" == "develop" ]]; then
              echo "Running on develop branch"
              # Add your develop branch steps here
            else
              echo "Invalid target branch specified for version 1.0.0-rc.1.0.0"
              exit 1
            fi
          else
            echo "Version not supported"
            exit 1
          fi
        env:
          TARGET_BRANCH: ${{ env.TARGET_BRANCH }}
